-- State 1: Enviado
INSERT INTO estado (Descritivo) VALUES ('Enviado');

-- State 2: Em análise
INSERT INTO estado (Descritivo) VALUES ('Em análise');

-- State 3: Concluído
INSERT INTO estado (Descritivo) VALUES ('Concluído');

-- State 4: Enviado para junta médica
INSERT INTO estado (Descritivo) VALUES ('Enviado para junta médica');

-- State 5: Cancelado
INSERT INTO estado (Descritivo) VALUES ('Cancelado');
